export default function Head() {
  return (
    <head>
      <title>Gaetan Santucci Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
    </head>
  )
}