export default function Head() {
  return (
    <head>
      <title>Gaetan Santucci Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/images/favicon.ico" />
    </head>
  )
}